openapi: 3.0.0
info:
  title: Service Lens API
  description: Lens API
  version: 1.0.0
paths:
  /v1/lense/templates:
    post:
      summary: Add a new template
      operationId: addTemplate
      tags:
        - templates
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK

components:
  schemas:
    Template:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        spec:
          type: string